RedCamel.WebUI/Controllers/API/ConventionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using RedCamel.Domain.Abstract;
using RedCamel.Domain.Entities;

namespace RedCamel.WebUI.Controllers.API
{
    public class ConventionController : ApiController
    {
        private IConventionRepository repository;

        public ConventionController(IConventionRepository shopSearchRepository)
        {
            this.repository = shopSearchRepository;
        }
        // GET: api/Convention
        public IEnumerable<Convention> Get(string country)
        {
            if (country == "undefined")
            { return repository.Conventions(); }
            else
            {
                return repository.Conventions(country);
            }
        }

        // GET: api/Convention/5
        public string Get()
        {
            return "value";
        }

        // POST: api/Convention
        public void Post([FromBody]string value)
        {
        }

        // PUT: api/Convention/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/Convention/5
        public void Delete(int id)
        {
        }
    }
}

RedCamel.WebUI/Controllers/NavController.cs
using RedCamel.Domain.Abstract;
using RedCamel.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RedCamel.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(CategoryEnum category = CategoryEnum.All, bool horizontalLayout = false)
        {
            ViewBag.SelectedCategory = category;
            /*
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category.ToString())
                .Distinct()
                .OrderBy(x => x);
                */

            IEnumerable<string> categories = repository.Categories
                    .Select(x => x.Name)
                    .Distinct()
                    .OrderBy(x => x);



            string viewName = horizontalLayout ? "MenuHorizontal" : "Menu";

            return PartialView(viewName,categories);
        }
    }
}

RedCamel.WebUI/Views/Shared/ProductSummary.cshtml
@model RedCamel.Domain.Entities.Product

<div class="well">    
   
    
    <img src="~/images/Uploads/@Model.Image1Name"  width="50px"/>
        
 

    <h3>        
    <strong>@Model.Name</strong>        
    
    <span class="pull-right label labelprimary">@Model.Price.ToString("c")</span>  
        <span class="pull-right label labelprimary">@Model.Condition</span>      
    </h3>    

    
        
    @using (Html.BeginForm("AddToCart", "Cart")){
        <div class="pull-right">@Html.HiddenFor(x => x.ID)           
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)            
        <input type="submit" class="btn btn-success" value="Add to cart" />       
        </div>    
    } 

    <span class="lead">desc: @Model.Description</span> 

</div> 

RedCamel.WebUI/Views/Shared/_AdminLayout.cshtml
@{    Layout = null; } 
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
   

    <title></title>
</head>
<body>
    <div>        @RenderBody()    </div>
</body>
</html> 

RedCamel.WebUI/Views/Shared/_FindMyLocalStore.cshtml
<div class="col-lg-12 text-center">
    <h2>Support your local comic shop!</h2>
    <p class="lead">Find your local store</p>
</div>
<div  ng-controller="LandingPageController">

    <style type="text/css">
        .initialMap {
            height: 0px;
            width: 100%;
            display: block;
        }

        .showMap {
            height: 200px;
            width: 100%;
            display: block;
            -webkit-transition: height 1s; /* Safari */
            transition: height 1s;
        }

        #searchfield{
            font-size:21px;
        }


        #autocomplete{
                margin-top: 10px;
    border-style: solid;
    border-color: white;
    background-color:#337ab7;
    color:white;
    text-align:center;
        }

        .autocomplete-suggestions{
                position: absolute;
    width: 144px;
    top: 3962.56px;
    left: 575px;
    max-height: 300px;
    z-index: 1000000;
    display: block;
    BORDER: white;
    border-style: solid;
   color: #fff;
    background-color: #337ab7;
    border-radius: 5px;
    font-size: 21px;
    overflow:hidden;
    padding:5px;
 
        }

        #searchSpinner{
               z-index: 100000;
    color: red;
    width: 100%;
        }
    </style>



   


    <div id="map" class="initialMap">

    </div>

    <div class="fa fa-5x fa-refresh fa-spin hidden text-center" id="searchSpinner"></div>

    <div id="searchfield" class="text-center">
        <form><input type="text" name="location" class="biginput" id="autocomplete"></form>
    </div>

    <div id="outputbox">
        <p id="outputcontent"></p>
    </div>


    <div id="ShopSearchController" class="text-center" ng-controller="ShopsearchController as vm">


        <!-- <button ng-click="vm.getShops('Derby')">Get Shops</button> -->



        <div ng-repeat="shop in vm.shops" class="bg-primary">
            <h3>{{shop.Name}} in {{shop.Town}}</h3>

            <!--<span>{{shop.Latitude}}</span>
            <span>{{shop.Longitude}}</span>-->
            <h4>Distance: {{shop.Distance.toFixed(2)}} miles</h4>
            <h4><i class="fa fa-phone"></i>&nbsp;{{shop.Phone}}</h4>
            <h4><i class="fa fa-external-link">&nbsp;</i>{{shop.WebPage}}</h4>
            <h4><i class="fa fa-external-link">&nbsp;</i>{{shop.Email}}</h4>
            <hr />
        </div>

    </div>


</div>

RedCamel.WebUI/Views/Shared/_LatestNews.cshtml
<div class="col-lg-12 text-center">
  
</div>


<div id="NewsDiv"  ng-controller="NewsController as vm">
    
    <button ng-click="vm.getNews()">Get News courtesy of CBR</button>
    <div id="NewsResults" class="panel-heading">
        <div class="panel panel-primary cbrPanel" ng-repeat="shop in vm.news">


            <a href="{{shop.Link}}" target="_blank">
                <div class="newsItem row">
                    <img class="cbrImage col-sm-2" src="{{shop.Image}}" />
                    <h3 class="visible hidden-xs cbrDescription col-sm-10">{{shop.Description}}</h3>
                    <p class="visible hidden-xs">{{shop.PublishedDate.Substring(0, 16)}}</p>
                    

                </div>
            </a>

        </div>
        <button id="ToggleNews" onclick="HideNews()">Click to hide</button>
    </div>
    

  
   
</div>

<script type="text/javascript">
    function CallNews() {
        
        angular.element(document.getElementById('NewsController')).scope().newsVm.getNews();
    }

    function HideNews() {
        $("#NewsResults").toggle();
        $("#ToggleNews").text("Click to show using ang");

        document.getElementById("news").scrollIntoView();

    }
</script>

RedCamel.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <link href="~/Content/RedCamel.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <title>@ViewBag.Title</title>

    <style>
        .navbar-right{
            float:right !important;
            margin-right: 15px;
            margin-left: 15px;
        }

         .navbar-left{
            float:left !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>

   @RenderSection("Scripts", false)
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle navbar-left " data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <span class="hidden-xs">RED CAMEL COMICS</span>
                    <div class="visible-xs">RED CAMEL</div>
                    <div class="visible-xs">COMICS</div>
                </a>


               @Html.Partial("~/Views/Shared/_Search.cshtml");
                

                @Html.Action("Summary", "Cart")
                

               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    
                </ul>

            </div>
            
    </div>
   </div>

    <div class="visible-xs horizontalMenuParent">
        @Html.Action("Menu", "Nav", new{ horizontalLayout=true})
    </div>
    <div class="row panel">
        <div id="categories" class="col-sm-3 hidden-xs">
            REfinements for slected subject - if no select then all
            @Html.Action("Menu","Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>

</body>
</html>

RedCamel.WebUI/Views/Shared/_LayoutNotShop.cshtml
<!DOCTYPE html>
<html style="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Find your local comic shop and support your local comic convention. All the latest news, reviews, shops and conventions related to comics!">
    <meta name="author" content="RedCamel">


    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/stylish-portfolio.css" rel="stylesheet" />

    

    <!-- Custom Fonts -->
    <link href="../font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    
    <title>@ViewBag.Title</title>
   
</head>
<body ng-app="RedCamelComicsApp">

    <!-- Navigation -->
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
            <li class="sidebar-brand">
                <a href="#top" onclick=$("#menu-close").click();>Red Camel Comics</a>
            </li>
            <li>
                <a href="#top" onclick=$("#menu-close").click();>Home</a>
            </li>
            <li>
                <a href="#about" onclick=$("#menu-close").click();>About</a>
            </li>
            <li>
                <a href="#news" onclick=$("#menu-close").click();>News</a>
            </li>
            <li>
                <a href="#conventions" onclick=$("#menu-close").click();>Conventions</a>
            </li>
            <li>
                <a href="#boxOffice" onclick=$("#menu-close").click();>Movies</a>
            </li>
            <li>
                <a href="#services" onclick=$("#menu-close").click();>Services</a>
            </li>
            <li>
                <a href="#findMyLocalStore" onclick=$("#menu-close").click();>Find My Local Store</a>
            </li>
            <li>
                <a href="#portfolio" onclick=$("#menu-close").click();>Portfolio</a>
            </li>
            <li>
                <a href="#footer" onclick=$("#menu-close").click();>Contact</a>
            </li>
        </ul>
    </nav>


    
        @RenderBody()
    

</body>
</html>

RedCamel.WebUI/Views/Shared/_Search.cshtml
<select>
    <option value="1">Hardback</option>
    <option value="1">TPB</option>
</select>

<select>
    <option value="2">X-Men</option>
    <option value="1">Hulk</option>
</select>

<input type="button" value="Go" onclick="Search()"/>
<a href="../Product/List/">grr</a>


<script type="text/javascript">
    function Search() {
        alert("_Search");
    }
</script>

RedCamel.WebUI/Views/Shared/_convention.cshtml
<div class="col-lg-12 text-center">
    <h2>Support your Convention!</h2>
    <p class="lead">Find your local convention</p>
</div>
<div  >

 

 
    <div id="Convention" class="text-center" ng-controller="ConventionsearchController as vm">

        <img src="~/img/United-Kingdom-icon.png" ng-click="vm.getConventions()" data-toggle="tooltip" data-placement="bottom" title="Get All UK Conventions"/>
        <img src="~/img/Scotland-icon.png" ng-click="vm.getConventions('Scotland')" data-toggle="tooltip" data-placement="bottom" title="Get All Scottish Conventions"/>
        <img src="~/img/England-icon.png" ng-click="vm.getConventions('England')" data-toggle="tooltip" data-placement="bottom" title="Get All English Conventions"/>
        

        <h1 ng-show="vm.conventionsAll">All</h1>
        <h1 ng-show="vm.conventionsScotland">Scotland</h1>
        <h1 ng-show="vm.conventionsEngland">England</h1>
        <h1 ng-show="vm.conventionsWales">Wales</h1>
        <h1 ng-show="vm.conventionsIreland">Ireland</h1>

        <div ng-repeat="convention in vm.conventions" class="bg-primary">
            <h3>{{convention.Name}}</h3>
            <h3>{{convention.Location}}</h3>

        </div>

    </div>


</div>